<?php
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\Core\Access\AccessResult;

/**
* Implements hook_theme().
*/
function trove_stories_theme($existing, $type, $theme, $path) {
  return [
    // 'field__node__title__custom_content_type' => [
    //     'template' => 'field--node--title--custom-content-type',
    //     'base hook' => 'field',
    // ],
  
    'webform__trove_stories' => [ //this defines a base hook that ensures 'trove_stories_theme_suggestions_webform_alter' is called
        'base hook' => 'webform',
    ],
    'field__node__title__trove_story_submission' => [
        'template' => 'field--node--title--trove-story-submission',
        'base hook' => 'field',
    ],
  ];
}

/* We add a custom template into the page title area */
// function trove_stories_theme_suggestions_block_alter(array &$suggestions, array &$variables) {

//     if ($variables['elements']['#base_plugin_id'] === 'page_title_block') {
//         if (\Drupal::service('trove_stories.common_services')->isTroveStoryRoute()) { 
//             $suggestions[] = 'block__trove_stories_admin_page_title';
//         }
//     }
// }



//hook into the form submission and create a new trove webform submission entry.
function trove_stories_webform_submission_presave(\Drupal\webform\WebformSubmissionInterface $webform_submission) {

    if ($webform_submission->getEntityTypeId() === 'webform_submission') {
        if (\Drupal::service('trove_stories.common_services')->isTroveStoryArea()) {

            //create trove story submission content
            $submissionData = $webform_submission->getData();

            $uploaded_media_ids = [];

            foreach($submissionData["upload_images"] as $file_id) {
                
                $file = File::load($file_id); 
                $media = Media::create([
                'bundle' => 'image',
                'uid' => \Drupal::currentUser()->id(),
                'status' => 1,
                'name' => $file->getFilename(),
                'field_media_image' => [
                    'target_id' => $file->id(),
                    'alt' => $file->getFilename(),
                    'title' => $file->getFilename(),
                    ],
                ]);

                $media->save();

                $uploaded_media_ids[] = ['target_id' => $media->id()];
            }

            //create new trove story display from the data
            $trove_story_submission = Node::create(array(
                'type' => 'trove_story_submission',
                'title' => $submissionData["story_title"],
                'langcode' => 'en',
                'uid' => \Drupal::currentUser()->id(), 
                'status' => 0,
                'field_tss_story_use' => $submissionData["use_trove"],
                'field_tss_story_about' => $submissionData["tell_us_about_your_story"],
                'field_tss_story_links' => $submissionData["trove_urls"],
                'field_tss_story_author' => $submissionData["display_name_story_author"],
                'field_tss_story_email' => $submissionData["email"],
                'field_tss_story_images' => $uploaded_media_ids,
                'field_tss_story_inspiration' => $submissionData["what_inspired_you_to_make_this_project"],
                'field_tss_story_name' => $submissionData["name"],
                'field_tss_story_postcode' => $submissionData["postcode"],
                'field_tss_story_title' => $submissionData["story_title"],
                'field_tss_story_year_of_birth' => $submissionData["year_of_birth"]
            ));

            $trove_story_submission->save();


        }
        
        echo "test";
    }
}


//this function stops published trove_story_submission content types from being viewed by the public if they are set to 'published'
function trove_stories_entity_access(Drupal\Core\Entity\EntityInterface $entity, $operation, Drupal\Core\Session\AccountInterface $account) {
    
    //let through all the non-node stuff like blocks etc.
    if ($entity->getEntityTypeId() !== 'node') {
        return AccessResult::neutral();
    }

    // 1. Check if the operation is 'view'.
    // 2. Check if the user is anonymous 
    // 3. Check if the node is the restricted content type.
    if ($operation === 'view' && $account->isAnonymous() && $entity->bundle() === 'trove_story_submission') {
        // Explicitly forbid access for anonymous users to this content type.
        // The 'setCacheMaxAge(0)' is important to prevent caching the forbidden result
        // on a user-specific page and showing it to other anonymous users.
        return AccessResult::forbidden()->setCacheMaxAge(0);
    }
    
    // For all other cases (e.g., authenticated users, different content types),
    // return neutral to allow other access checkers to determine access.
    return AccessResult::neutral();
}

// function trove_stories_views_pre_view(ViewExecutable $view, $display_id) {
//     if ($view->id() === 'trove_stories_submissions' && $display_id === 'page_1') {
//         echo "test";
//         $newfield = array();
//         $newfield['id'] = 'field_whatever';
//         $newfield['table'] = 'node.field_whatever';
//         $newfield['field'] = 'field_whatever';
//         $view->setHandler($view->current_display, 'field', 'field_whatever', $newfield);
//     }
   
// }

/**
 * Implements hook_views_pre_render().
 */
// function trove_stories_views_pre_render(ViewExecutable $view) {
    
//     if ($view->id() === 'trove_stories_submissions' && $view->current_display === 'page_1') {
//        // echo "test";

//        $columns = $view->field;
//         foreach ($view->result as $row) {
//             $row->my_custom_column = "testcustom column";
//             $fields = $row->field;
//             echo "1";
//         }

//         echo "here";
//   }

// }

/**
* Implements hook_preprocess_html().
*/
/*
    Add custom css style sheets and body class for Trove Stories admin pages.
*/
function trove_stories_preprocess_html(&$variables) {

    if (\Drupal::service('trove_stories.common_services')->isTroveStoryArea()) { 
        $variables['#attached']['library'][] = 'trove_stories/trove_stories_library'; //add our stylesheet
        $variables['attributes']['class'][] = 'troveStories'; //add body class
    }
}

/**
 * Implements hook_library_info_build().
 * This is to add the recaptcha API library from google
 * with the parameter reCAPTCHA_site_key fetched from settings.
 */
function trove_stories_library_info_build() {
    
    $config = \Drupal::config('trove_stories.settings');
    $recaptcha_site_key = $config->get('trove_stories_recaptcha_site_key');

    if (empty($recaptcha_site_key)) {
        // If the key is not set, return an empty array for this library.
        return [];
    }

    $recapta_url = 'https://www.google.com/recaptcha/api.js?render=' . $recaptcha_site_key;

    $libraries['trove_recaptcha_api'] = [
        //'version' => '',
        'header' => TRUE, // Load in the <head>
        'js' => [
            // The dynamically generated URL is used as the key.
            $recapta_url => [
                'type' => 'external',
                'minified' => TRUE,
            ],
        ],
        //Set the cache tags so the library is rebuilt when the key changes.
        'metadata' => [
            'cache' => [
                'tags' => $config->getCacheTags(),
            ],
        ],
    ];

    return $libraries;
}

/**
 * Implements hook_page_attachments().
 * we use this to insert the recaptcha key from the config into the javascript libray/file that executes the recaptcha api call.
 */
function trove_stories_page_attachments(array &$attachments) {
    $recaptcha_site_key = \Drupal::config('trove_stories.settings')->get('trove_stories_recaptcha_site_key');

    // Attach the value to drupalSettings under your module's namespace.
    $attachments['#attached']['drupalSettings']['trove_stories']['trove_stories_recaptcha_site_key'] = $recaptcha_site_key;

    // Also attach your JavaScript library.
    $attachments['#attached']['library'][] = 'trove_stories/trove_stories_recaptcha';
}

/**
 * Implements hook_form_alter().
 * We add in custom js/css from the module library into this specific form
 */
function trove_stories_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

    $selected_form_id = \Drupal::service('trove_stories.common_services')->getTroveStoriesFormId();

    if (!empty($form['#webform_id']) && $selected_form_id === $form['#webform_id']) {
        $form['#attached']['library'][] = 'trove_stories/trove_recaptcha_api'; //this is a dynamically created libray in hook_library_info_build
        $form['#attached']['library'][] = 'trove_stories/trove_stories_recaptcha';
    }
    
}

/* We add a custom template into the trove stories form  */
function trove_stories_theme_suggestions_webform_alter(array &$suggestions, array $variables) {

    $selected_form_id = \Drupal::service('trove_stories.common_services')->getTroveStoriesFormId();

    //if ($variables['element']['#webform_id'] == 'trove_story') {
    if ($variables['element']['#webform_id'] == $selected_form_id) {
        //look for this 'webform--trove-stories.html' template in modules/trove_stories/templates
        $suggestions[] = 'webform__trove_stories';
    }
}

/**
 * Implements hook_node_view_alter().
 */
/*
    Individual submission pages - add extra buttons
*/
function trove_stories_node_view_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity) {
    
        if ($entity->bundle() !== 'trove_story_submission') {
            return;
        }

        //create a fieldset for the buttons
        $build['trove_story_submissions_buttons'] = [
            '#type' => 'fieldset',
            '#title' => '',
            '#description' => '',
            '#attributes' => [
                'class' => ['trove_story_submission_buttons'],
            ],
            '#weight' => -10
        ];

        //create the 'back to submissions' button
        $submissions_route_url = Url::fromRoute('view.trove_stories_views.page_1');
        
        $build['trove_story_submissions_buttons']['back_to_trove_story_submissions_button'] = [
            '#type' => 'link',
            '#title' => \Drupal::service('string_translation')->translate('< Back to trove story submissions'),
            '#url' => $submissions_route_url,
            '#prefix' => '<div class="trove-story-web-story-button-wrapper">',
            '#suffix' => '</div>',
            '#attributes' => [
                'class' => ['button', 'button--primary'],
            ],
            '#weight' => -10
        ];

        //create the 'convert to trove story' button
        $query_string_options['submission_id'] = $entity->id();
        $convert_route_url = Url::fromRoute('trove_stories.webform_submission.create_trove_story_web_story');
        $convert_route_url->setOption('query', $query_string_options);

        $build['trove_story_submissions_buttons']['convert_to_trove_story_web_story_button'] = [
            '#type' => 'link',
            '#title' => \Drupal::service('string_translation')->translate('Convert to Trove Story Website Story'),
            '#url' => $convert_route_url,
            '#prefix' => '<div class="trove-story-web-story-button-wrapper btn2">',
            '#suffix' => '</div>',
            '#weight' => -10,
            '#attributes' => [
                'class' => ['button', 'button--primary'],
            ],
        ];

        //$build['convert_to_trove_story_button']['#weight'] = -10;
        //$build['convert_to_trove_story_web_story_button']['#weight'] = 150;
    

}


/**
 * Implements hook_install().
 */
function trove_stories_install() {

    /***** 
        set default form to "trove_story" which should be installed from the config/optional install ymls
    ****/    
    $selected_form = \Drupal::service('trove_stories.common_services')->getTroveStoriesFormId();
    if (is_null($selected_form)) {
        $config = \Drupal::getContainer()->get('config.factory')->getEditable('trove_stories.settings');
        $config->set('trove_stories_selected_form', 'trove_story');
        $config->save();
    }

    /***** 
        set access permissions for new content types, these are set at:
        admin/structure/types/manage/trove_story_submission/permissions
        admin/structure/types/manage/trove_story_web_story/permissions
        We do this in the hook_install because the yml config files
        require ALL permissions to be set and we don't want to accidently
        edit or change any current permissions outside the scope of this modules
        content types.
    ****/
    $roles = ['trove_editor', 'trove_author', 'trove_administrator'];

    foreach($roles as $role) {
        /** @var \Drupal\user\RoleInterface $loadedRole */
        $loadedRole = \Drupal::entityTypeManager()->getStorage('user_role')->load($role);

        /** trove_story_submission  **/
        $loadedRole->grantPermission('create trove_story_submission content');
        $loadedRole->grantPermission('delete any trove_story_submission content');
        $loadedRole->grantPermission('delete own trove_story_submission content');
        $loadedRole->grantPermission('delete trove_story_submission revisions');
        $loadedRole->grantPermission('edit any trove_story_submission content');
        $loadedRole->grantPermission('edit own trove_story_submission content');
        $loadedRole->grantPermission('revert trove_story_submission revisions');
        $loadedRole->grantPermission('view trove_story_submission revisions');

        /** trove_story_web_story  **/
        $loadedRole->grantPermission('create trove_story_web_story content');
        $loadedRole->grantPermission('delete any trove_story_web_story content');
        $loadedRole->grantPermission('delete own trove_story_web_story content');
        $loadedRole->grantPermission('delete trove_story_web_story revisions');
        $loadedRole->grantPermission('edit any trove_story_web_story content');
        $loadedRole->grantPermission('edit own trove_story_web_story content');
        $loadedRole->grantPermission('revert trove_story_web_story revisions');
        $loadedRole->grantPermission('view trove_story_web_story revisions');

        $loadedRole->save();
    }


    /***
        For the Trove Stories form, set default columns to display
        to set custom columns, get the full form from state API, then
        update the array 'results.custom.columns' with the preferred column keys to display.
    ****/
    // $state = \Drupal::state();
    // $form_data = $state->get('webform.webform.trove_story', []); 
    // $diplayed_cols = [ // these keys can be found by debugging /WebformResultsCustomForm.php
    //     'serial',
    //     'element__email',
    //     'element__story_title',
    //     'element__name',
    //     'element__year_of_birth',
    //     'element__display_name_story_author',
    //     //'sid',
    //     'created',
    //     'operations'
    // ];
    
    // $form_data['results.custom.columns'] = $diplayed_cols;
    // $state->set('webform.webform.trove_story', $form_data);

    /***
        set new action 'create_trove_story_action' to 'on' in the 'admin/structure/webform/config/submissions' area.
        this enables the bulk action on form submissions that converts a submission to a trove story.
        REMOVED: actions not really needed and too much extra work when we can use a button per individual 
        submission to create trove story.
    ****/
    // $actions = \Drupal::entityTypeManager()->getStorage('action')->loadMultiple();

    // if (!is_null($actions['create_trove_story_action'])) {
        
    //     $config_factory = \Drupal::service('config.factory');
    //     $webFormconfig = $config_factory->getEditable('webform.settings');

    //     $submission_bulk_actions = $webFormconfig->get("settings.webform_submission_bulk_form_actions");

    //     // 'webform_submission_bulk_form_actions' array lists the ENABLED items - disabled items don't exist in the array
    //     // so we add the action to the array.
    //     // the admin page that renders these config items is the buildBulkOperations() function in WebformAdminConfigBaseForm.php
    //     if (!in_array('create_trove_story_action', $submission_bulk_actions)) {
    //         $submission_bulk_actions[] = 'create_trove_story_action';
    //         $webFormconfig->set('settings.webform_submission_bulk_form_actions', $submission_bulk_actions);
    //         $webFormconfig->save();
    //     }
    // }

}



