<?php
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
/**
* Implements hook_theme().
*/
function trove_stories_theme($existing, $type, $theme, $path) { //note: can't do runtime logic here

        return [
            'page__trove_stories_gallery_page' => [ //this is the main content area for /trove-stories - eg, the gallery/listing page.
                //'variables' => ['title' => NULL, 'data' => []],
                'variables' => [],
            ],
            'webform__trove_stories' => [ //this defines a base hook that ensures 'trove_stories_theme_suggestions_webform_alter' is called
                'base hook' => 'webform',
            ],
            'form-element__webform__tswf_banner_message' => [ //overwrite the header/banner html markup field
                'base hook' => 'form_element',
            ],
            // 'webform_html_editor_markup' => [ //overwrite the html editor markup content for the header/banner
            //     'base hook' => 'webform_html_editor_markup',
            // ],
            'field__node__title__trove_story_submission' => [
                'template' => 'field--node--title--trove-story-submission',
                'base hook' => 'field',
            ],

            'input__submit_trove_stories' => [ //register new hook suggestion implemented in trove_stories_theme_suggestions_input_alter()
                'base hook' => 'input__submit',
            ],
            // 'breadcrumb__trove_stories' => [ //register new hook suggestion used in trove_stories_theme_suggestions_breadcrumb_alter() below
            //     'base hook' => 'breadcrumb',
            // ]
        ];
}

/* We add a custom template form the banner form element  */
function trove_stories_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {
    
    if (empty($variables['element']['#webform'])) return;

    $selected_form_id = \Drupal::service('trove_stories.common_services')->getTroveStoriesFormId();

    if (   
        $variables['element']['#webform'] === $selected_form_id &&
        $variables['element']['#webform_id'] === 'trove_story--tswf_banner_message'
        ) {
            $suggestions[] = 'form-element__webform__tswf_banner_message';
    }
}

/* We add a custom template form the html content of the header/banner  */
// function trove_stories_theme_suggestions_webform_html_editor_markup_alter(array &$suggestions, array $variables) {
//     $selected_form_id = \Drupal::service('trove_stories.common_services')->getTroveStoriesFormId();

// }

/* We add a custom template into the trove stories form  */
function trove_stories_theme_suggestions_webform_alter(array &$suggestions, array $variables) {

    $selected_form_id = \Drupal::service('trove_stories.common_services')->getTroveStoriesFormId();

    //if ($variables['element']['#webform_id'] == 'trove_story') {
    if ($variables['element']['#webform_id'] == $selected_form_id) {
        //look for this 'webform--trove-stories.html' template in modules/trove_stories/templates
        $suggestions[] = 'webform__trove_stories';
    }
}

/*
We override the submit button template for the trove stories form, note there are multiple 
submit buttons, so we directly check the id for 'edit-submit' which is the main form submission button.
*/
function trove_stories_theme_suggestions_input_alter(array &$suggestions, array $variables) {

    if (empty($variables['element']['#id'])) return;
    
    $id = $variables['element']['#id'];

    if ($variables['theme_hook_original'] === 'input__submit' && $id === 'edit-submit') {
       
        if (\Drupal::service('trove_stories.common_services')->isTroveStoryForm()) {

            $suggestions[] = 'input__submit_trove_stories';
        }
    }
    
}

/*
    On the trove stories gallery listing page and trove main form page
     remove the top region that contains the breadcrumbs
    this is so there is space to put in the banners
*/
function trove_stories_preprocess_page(&$variables) {
    $route_match = \Drupal::routeMatch();
    $route_name = $route_match->getRouteName();
    if ($route_name === "trove_stories.trove_stories") {
        unset($variables['page']['content_top']);
    }

    if (\Drupal::service('trove_stories.common_services')->isTroveStoryForm()) {
        unset($variables['page']['content_top']);
    }

}


/* We add a custom template into the page title area */
// function trove_stories_theme_suggestions_block_alter(array &$suggestions, array &$variables) {

//     if ($variables['elements']['#base_plugin_id'] === 'page_title_block') {
//         if (\Drupal::service('trove_stories.common_services')->isTroveStoryRoute()) { 
//             //$suggestions[] = 'block__trove_stories_admin_page_title';
//             $suggestions[] = 'trove_stories_input__submit.html';
//         }
//     }
// }



//hook into the form submission and create a new trove webform submission entry.
function trove_stories_webform_submission_presave(\Drupal\webform\WebformSubmissionInterface $webform_submission) {

    if ($webform_submission->getEntityTypeId() === 'webform_submission') { //note this is the webform submission content type, not the trove stories submission content type
        if (\Drupal::service('trove_stories.common_services')->isTroveStoryForm()) {

            //create trove story submission content
            $submissionData = $webform_submission->getData();

            $uploaded_media_ids = [];

            /*
            Note: we are creating a new image that is of the 'Media type' > 'image'
            see: https://trove.ddev.site/admin/structure/media 'image' is a type.
            We are doing this because the webform does not create image media types for their
            uploads, only raw files. We convert to media image type so we 
            can fetch and edit the media via standard entity browsers and such.

            Note that our webform image upload field on the webform is set to 
            save the file uploads in the private files directory. This is to
            stop any random uploading dodgy files that the public can then scrape.
        
            So even though the 'image' Media content type is has a default setting 
            set to 'public files' as the upload destination, because we are setting 
            the target_id of it to the original webform image target_id - it ends up referencing 
            a private file path.
            */
            if (!empty($submissionData["tswf_upload_images"])) {
                foreach($submissionData["tswf_upload_images"] as $file_id) {
                    $file = File::load($file_id); //we load the webform file upload that is stored in the private directory
                    //$new_file_id = $file->id();
                    $media = Media::create([ //we create a new 'image' media type that references this privately stored file.
                        'bundle' => 'image',
                        'uid' => \Drupal::currentUser()->id(),
                        'status' => 1,
                        'name' => $file->getFilename(),
                        'field_media_image' => [
                            'target_id' => $file->id(),
                            'alt' => $file->getFilename(),
                            'title' => $file->getFilename(),
                            ],
                    ]);

                    $media->save();
                    //$new_media_id = $media->id();
                    $uploaded_media_ids[] = ['target_id' => $media->id()];
                }
            }
            

            //create new trove story display from the data
            $trove_story_submission = Node::create(array(
                'type' => 'trove_story_submission',
                'title' => $submissionData["tswf_story_title"],
                'langcode' => 'en',
                'uid' => \Drupal::currentUser()->id(), 
                'status' => 0,
                'field_tss_story_use' => $submissionData["tswf_how_you_use_trove"],
                'field_tss_story_about' => $submissionData["tswf_about_your_story"],
                'field_tss_story_links' => $submissionData["tswf_links"],
                'field_tss_story_author' => $submissionData["tswf_display_name_story_author"],
                'field_tss_story_email' => $submissionData["tswf_email"],
                'field_tss_story_images' => $uploaded_media_ids,
                'field_tss_story_inspiration' => $submissionData["tswf_inspired"],
                'field_tss_story_name' => $submissionData["tswf_name"],
                'field_tss_story_postcode' => $submissionData["tswf_postcode"],
                'field_tss_story_title' => $submissionData["tswf_story_title"],
                'field_tss_story_year_of_birth' => $submissionData["tswf_year_of_birth"]
            ));

            $trove_story_submission->save();

        }
    }
}


//this function stops published trove_story_submission content types from being viewed by the public if they are set to 'published'
function trove_stories_entity_access(Drupal\Core\Entity\EntityInterface $entity, $operation, Drupal\Core\Session\AccountInterface $account) {
    
    //let through all the non-node stuff like blocks etc.
    if ($entity->getEntityTypeId() !== 'node') {
        return AccessResult::neutral();
    }

    // 1. Check if the operation is 'view'.
    // 2. Check if the user is anonymous 
    // 3. Check if the node is the restricted content type.
    if ($operation === 'view' && $account->isAnonymous() && $entity->bundle() === 'trove_story_submission') {
        // Explicitly forbid access for anonymous users to this content type.
        // The 'setCacheMaxAge(0)' is important to prevent caching the forbidden result
        // on a user-specific page and showing it to other anonymous users.
        return AccessResult::forbidden()->setCacheMaxAge(0);
    }
    
    // For all other cases (e.g., authenticated users, different content types),
    // return neutral to allow other access checkers to determine access.
    return AccessResult::neutral();
}

/**
* Implements hook_preprocess_html().
*/
/*
    Add custom css style sheets and body class for Trove Stories pages.
*/
function trove_stories_preprocess_html(&$variables) {

    if (\Drupal::service('trove_stories.common_services')->isTroveStoryForm() 
        || \Drupal::service('trove_stories.common_services')->isTroveStorySubmission()) { 
        $variables['#attached']['library'][] = 'trove_stories/trove_stories_css_library'; //add our main stylesheet
        $variables['attributes']['class'][] = 'troveStories'; //add body class to all trove stories areas
    }

    if (\Drupal::service('trove_stories.common_services')->isTroveStoryForm()) { 
        $variables['#attached']['library'][] = 'trove_stories/trove_stories_form_css_library'; //add our form css file only for trove form page
    }

    if (\Drupal::service('trove_stories.common_services')->isTroveStorySubmission()) { 
        $variables['#attached']['library'][] = 'trove_stories/trove_stories_submission_css_library'; //add our submission page style sheet.
    }
}

/**
 * Implements hook_library_info_build().
 * This is to add the recaptcha API library from google
 * with the parameter reCAPTCHA_site_key fetched from settings.
 */
function trove_stories_library_info_build() {
    
    $config = \Drupal::config('trove_stories.settings');
    $recaptcha_site_key = $config->get('trove_stories_recaptcha_site_key');

    if (empty($recaptcha_site_key)) {
        // If the key is not set, return an empty array for this library.
        return [];
    }

    $recapta_url = 'https://www.google.com/recaptcha/api.js?render=' . $recaptcha_site_key;

    $libraries['trove_recaptcha_api'] = [
        //'version' => '',
        'header' => TRUE, // Load in the <head>
        'js' => [
            // The dynamically generated URL is used as the key.
            $recapta_url => [
                'type' => 'external',
                'minified' => TRUE,
            ],
        ],
        //Set the cache tags so the library is rebuilt when the key changes.
        'metadata' => [
            'cache' => [
                'tags' => $config->getCacheTags(),
            ],
        ],
    ];

    return $libraries;
}

/**
 * Implements hook_page_attachments().
 * we use this to insert the recaptcha key from the config into the javascript libray/file that executes the recaptcha api call.
 */
function trove_stories_page_attachments(array &$attachments) {

    $isTroveForm = \Drupal::service('trove_stories.common_services')->isTroveStoryForm();
    if (!$isTroveForm) return;

    $recaptcha_site_key = \Drupal::config('trove_stories.settings')->get('trove_stories_recaptcha_site_key');

    // Attach the value to drupalSettings under your module's namespace.
    $attachments['#attached']['drupalSettings']['trove_stories']['trove_stories_recaptcha_site_key'] = $recaptcha_site_key;

    // Also attach your JavaScript library.
    $attachments['#attached']['library'][] = 'trove_stories/trove_stories_recaptcha';
}

/**
 * Implements hook_form_alter().
 * We add in custom js/css from the module library into this specific form
 */
function trove_stories_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

    //$selected_form_id = \Drupal::service('trove_stories.common_services')->getTroveStoriesFormId();

    //also check route

    //$current_form = $form['#webform_id'];

    //if (!empty($form['#webform_id']) && $selected_form_id === $form['#webform_id']) {
    if (\Drupal::service('trove_stories.common_services')->isTroveStoryForm()) {
        $form['#attached']['library'][] = 'trove_stories/trove_recaptcha_api'; //this is a dynamically created libray in hook_library_info_build
        $form['#attached']['library'][] = 'trove_stories/trove_stories_recaptcha';
    }
    
}

/**
 * Implements hook_form_FORM_ID_alter().
 * We hook into the trove story form on load and add a new validation function callback 
 * the validation function is called only on form submission.
 * note the form id is not 'trove_story' but 'webform-submission-trove-story-add-form' these are the same forms though.
 */

function trove_stories_form_webform_submission_trove_story_add_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
    $form['#validate'][] = '_trove_stories_webform_validate'; //we tell the form that we have a custom validation function
}

//this is our implementation of the custom form validation function.
function _trove_stories_webform_validate(array &$form, FormStateInterface $form_state) {

    $recaptcha_hidden_token = $form_state->getValue('tswf_recaptcha_token');

    if (empty($recaptcha_hidden_token)) {
        $form_state->setErrorByName(NULL, 'Invalid form submission');
        return;
    }

    //if we have the token, then send to recaptcha to verify
    $config = \Drupal::config('trove_stories.settings');
    $recaptcha_secret_key = $config->get('trove_stories_recaptcha_secret_key');

    $url = 'https://www.google.com/recaptcha/api/siteverify';

    $post_data = [
        'secret' => $recaptcha_secret_key,
        'response' => $recaptcha_hidden_token,
    ];

    $ip_address = \Drupal::request()->getClientIp(); //locally this returns the docker container ip.

    if ($ip_address) {
        $post_data['remoteip'] = $ip_address;
    }

    $options = [
        'http' => [
            'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
            'method'  => 'POST',
            'content' => http_build_query($post_data),
        ],
    ];
    $context  = stream_context_create($options);

    $result = file_get_contents($url, false, $context);

    if ($result === false) {
        // Log the error for debugging purposes (optional)
        $form_state->setErrorByName(NULL, 'reCAPTCHA validation failed');
        return;
    }

    $response_data = json_decode($result, true);
    // $response_data['success'];
    // $response_data['challenge_ts'];
    // $response_data['hostname'];
    // $response_data['score'];
    // $response_data['action'];

    if ($response_data && $response_data['success'] === true) {
        if ($response_data['score'] < 0.5) {
            $form_state->setErrorByName(NULL, 'reCAPTCHA validation failed');
            return;
        }
    }
}

/**
 * Implements hook_node_view_alter().
 */
/*
    Individual submission pages - add extra buttons
*/
function trove_stories_node_view_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity) {
    
        if ($entity->bundle() !== 'trove_story_submission') {
            return;
        }

        //create a fieldset for the buttons
        $build['trove_story_submissions_buttons'] = [
            '#type' => 'fieldset',
            '#title' => '',
            '#description' => '',
            '#attributes' => [
                'class' => ['trove_story_submission_buttons'],
            ],
            '#weight' => -10
        ];

        //create the 'back to submissions' button
        $submissions_route_url = Url::fromRoute('view.trove_stories_views.page_1');
        
        $build['trove_story_submissions_buttons']['back_to_trove_story_submissions_button'] = [
            '#type' => 'link',
            '#title' => \Drupal::service('string_translation')->translate('< Back to trove story submissions'),
            '#url' => $submissions_route_url,
            '#prefix' => '<div class="trove-story-web-story-button-wrapper">',
            '#suffix' => '</div>',
            '#attributes' => [
                'class' => ['button', 'button--primary'],
            ],
            '#weight' => -10
        ];

        //create the 'convert to trove story' button
        $query_string_options['submission_id'] = $entity->id();
        $convert_route_url = Url::fromRoute('trove_stories.webform_submission.create_trove_story_web_story');
        $convert_route_url->setOption('query', $query_string_options);

        $build['trove_story_submissions_buttons']['convert_to_trove_story_web_story_button'] = [
            '#type' => 'link',
            '#title' => \Drupal::service('string_translation')->translate('Convert to Trove Story Website Story'),
            '#url' => $convert_route_url,
            '#prefix' => '<div class="trove-story-web-story-button-wrapper btn2">',
            '#suffix' => '</div>',
            '#weight' => -10,
            '#attributes' => [
                'class' => ['button', 'button--primary'],
            ],
        ];

        //$build['convert_to_trove_story_button']['#weight'] = -10;
        //$build['convert_to_trove_story_web_story_button']['#weight'] = 150;
    

}


/**
 * Implements hook_install().
 */
function trove_stories_install() {

    /***** 
        set default form to "trove_story" which should be installed from the config/optional install ymls
    ****/    
    $selected_form = \Drupal::service('trove_stories.common_services')->getTroveStoriesFormId();
    if (is_null($selected_form)) {
        $config = \Drupal::getContainer()->get('config.factory')->getEditable('trove_stories.settings');
        $config->set('trove_stories_selected_form', 'trove_story');
        $config->save();
    }

    /***** 
        set access permissions for new content types, these are set at:
        admin/structure/types/manage/trove_story_submission/permissions
        admin/structure/types/manage/trove_story_web_story/permissions
        We do this in the hook_install because the yml config files
        require ALL permissions to be set and we don't want to accidently
        edit or change any current permissions outside the scope of this modules
        content types.
    ****/
    $roles = ['trove_editor', 'trove_author', 'trove_administrator'];

    foreach($roles as $role) {
        /** @var \Drupal\user\RoleInterface $loadedRole */
        $loadedRole = \Drupal::entityTypeManager()->getStorage('user_role')->load($role);

        /** trove_story_submission  **/
        $loadedRole->grantPermission('create trove_story_submission content');
        $loadedRole->grantPermission('delete any trove_story_submission content');
        $loadedRole->grantPermission('delete own trove_story_submission content');
        $loadedRole->grantPermission('delete trove_story_submission revisions');
        $loadedRole->grantPermission('edit any trove_story_submission content');
        $loadedRole->grantPermission('edit own trove_story_submission content');
        $loadedRole->grantPermission('revert trove_story_submission revisions');
        $loadedRole->grantPermission('view trove_story_submission revisions');

        /** trove_story_web_story  **/
        $loadedRole->grantPermission('create trove_story_web_story content');
        $loadedRole->grantPermission('delete any trove_story_web_story content');
        $loadedRole->grantPermission('delete own trove_story_web_story content');
        $loadedRole->grantPermission('delete trove_story_web_story revisions');
        $loadedRole->grantPermission('edit any trove_story_web_story content');
        $loadedRole->grantPermission('edit own trove_story_web_story content');
        $loadedRole->grantPermission('revert trove_story_web_story revisions');
        $loadedRole->grantPermission('view trove_story_web_story revisions');

        $loadedRole->save();
    }


    /***
        For the Trove Stories form, set default columns to display
        to set custom columns, get the full form from state API, then
        update the array 'results.custom.columns' with the preferred column keys to display.
    ****/
    // $state = \Drupal::state();
    // $form_data = $state->get('webform.webform.trove_story', []); 
    // $diplayed_cols = [ // these keys can be found by debugging /WebformResultsCustomForm.php
    //     'serial',
    //     'element__email',
    //     'element__story_title',
    //     'element__name',
    //     'element__year_of_birth',
    //     'element__display_name_story_author',
    //     //'sid',
    //     'created',
    //     'operations'
    // ];
    
    // $form_data['results.custom.columns'] = $diplayed_cols;
    // $state->set('webform.webform.trove_story', $form_data);

    /***
        set new action 'create_trove_story_action' to 'on' in the 'admin/structure/webform/config/submissions' area.
        this enables the bulk action on form submissions that converts a submission to a trove story.
        REMOVED: actions not really needed and too much extra work when we can use a button per individual 
        submission to create trove story.
    ****/
    // $actions = \Drupal::entityTypeManager()->getStorage('action')->loadMultiple();

    // if (!is_null($actions['create_trove_story_action'])) {
        
    //     $config_factory = \Drupal::service('config.factory');
    //     $webFormconfig = $config_factory->getEditable('webform.settings');

    //     $submission_bulk_actions = $webFormconfig->get("settings.webform_submission_bulk_form_actions");

    //     // 'webform_submission_bulk_form_actions' array lists the ENABLED items - disabled items don't exist in the array
    //     // so we add the action to the array.
    //     // the admin page that renders these config items is the buildBulkOperations() function in WebformAdminConfigBaseForm.php
    //     if (!in_array('create_trove_story_action', $submission_bulk_actions)) {
    //         $submission_bulk_actions[] = 'create_trove_story_action';
    //         $webFormconfig->set('settings.webform_submission_bulk_form_actions', $submission_bulk_actions);
    //         $webFormconfig->save();
    //     }
    // }

}



